# docker-compose.yml for Task 3
version: '3'

services:
  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task3
    ports:
      - "9000:9000"

  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task3
    ports:
      - "5252:5252"

